### ISSUE TITLE
change systemID parameter to be projectID

### ISSUE THREAD

**Issue by karlgroves** [egauci/grunt-tenon-client#3]
@tenonapi changed systemID to be projectID

**Comment by egauci** [comment]
Thanks Karl - will take care of this tomorrow (Friday).

**Comment by egauci** [comment]
This doesn't actually involve the grunt task. The only place that this parameter appears is in src/index.js which you can run as "node src/index" (use --help for options). The grunt task doesn't care and just passes any options it doesn't use itself to tenon.

Fixed in 0.7.0.
